---
# tasks file for ansible-role-bowtie2

- name: Load the bowtie2 module
  command: module load bowtie2

- name: Create output directories
  file: path={{ data }}/{{ item }} state=directory mode=0777
  with_items:
    - bowtie2
    - bowtie2/out
    - bowtie2/sam

- name: Copy scripts to target machine
  copy: src="{{ role_path }}/files/{{ item }}" dest="{{ data }}/bowtie2"
  with_items:
    - submit.sh
    - bowtie2.sh

- name: Submit jobs to cluster
  command: "sh {{ data }}/bowtie2/submit.sh {{ data }}"
