---
# tasks file for ansible-role-dada2-run

- name: Create output directories
  file: path={{ data }}/{{ item }} state=directory mode=0777
  with_items:
    - dada
    - software

- name: Get the bbmap software
  get_url:
    url: https://sourceforge.net/projects/bbmap/files/BBMap_37.95.tar.gz
    checksum: md5:bb4ab33674e85beb3e69e2afc5436243
    dest: "{{ data }}/software"

- name: Extract bbmap
  unarchive:
    src: "{{ data }}/software/BBMap_37.95.tar.gz"
    dest: "{{ data }}/software"
    remote_src: true

- name: Get the Greengenes db
  get_url:
    url: ftp://greengenes.microbio.me/greengenes_release/gg_13_5/gg_13_8_otus.tar.gz
    dest: "{{ data }}/software"

- name: Extract Greengenes
  unarchive:
    src: "{{ data }}/software/gg_13_8_otus.tar.gz"
    dest: "{{ data }}/software"
    remote_src: true

- name: Copy scripts to target machine
  copy: src="{{ role_path }}/files/{{ item }}" dest="{{ data }}/dada"
  with_items:
    - submit.sh
    - _submit.sh
    - queue.sh
    - read_length.py
    - dada_sample_inference.sh
    - dada_sample_inference.R
    - dada_chimera_taxonomy.sh
    - dada_chimera_taxonomy.R
    - silva_nr_v128_train_set.fa.gz
    - combine.sh

- name:  Make sure the queue is empty
  command: "sh {{ data }}/dada/queue.sh {{ user }}"

- name: Generate Combined file
  command: "sh {{ data }}/dada/combine.sh {{ data }}"

- name: Generate histogram
  command: "sh {{ data }}/software/bbmap/readlength.sh in={{ data }}/dada/combined.fastq out={{ data }}/dada/hist.txt bin=1"

- name: Submit jobs to cluster
  command: "sh {{ data }}/dada/submit.sh {{ data }} {{ qname }}"
